version: '3.9'

services:
  loghi-wrapper:
    build:
      context: ..  # Points to the root directory
      dockerfile: docker-wrapper/Dockerfile
    image: loghi-wrapper:latest
    container_name: loghi-wrapper
    command: start
    volumes:
      # Mount Docker socket for Docker-in-Docker functionality
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount root directory
      - ../:/app/root:ro
      # Mount input and output directories
      - ./input:/app/data/input:ro
      - ./output:/app/data/output
      # Mount local directories for logs and config
      - ./logs:/app/logs
      - ./config:/app/config:ro
      - ./models:/app/models
      # Mount Git modules
      - ../laypa:/app/modules/laypa:ro
      - ../loghi-htr:/app/modules/loghi-htr:ro
      - ../loghi-tooling:/app/modules/loghi-tooling:ro
      - ../prima-core-libs:/app/modules/prima-core-libs:ro
      # Mount temp workspace as a named volume
      - loghi_temp_workspace:/app/temp_workspace
    environment:
      - TZ=Europe/Amsterdam
      - ENABLE_CRON=true
      - USE_GIT_SUBMODULES=false
      # Set environment variables for paths
      - LOGHI_DATA_DIR=/app/data
      - LOGHI_CONFIG_DIR=/app/config
      - LOGHI_LOGS_DIR=/app/logs
      - LOGHI_MODELS_DIR=/app/models
      - LOGHI_MODULES_DIR=/app/modules
    restart: unless-stopped
    user: root  # Run as root to ensure proper permissions
    privileged: true  # Required for Docker-in-Docker functionality
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  logs:
  config:
  models:
  loghi_temp_workspace:
    name: loghi_temp_workspace 