# version: '3.9'

services:
  loghi-wrapper:
    build:
      context: ..
      dockerfile: ./docker-wrapper/Dockerfile
    image: loghi-wrapper:latest
    container_name: loghi-wrapper
    volumes:
      # # Mount Docker socket for Docker-in-Docker functionality
      # - /var/run/docker.sock:/var/run/docker.sock
      # # Option 1: Mount Git modules (uncomment if using mounted modules)
      # - ../laypa:/app/modules/laypa
      # - ../loghi-htr:/app/modules/loghi-htr
      # - ../loghi-tooling:/app/modules/loghi-tooling
      # - ../prima-core-libs:/app/modules/prima-core-libs
      # # Mount Workspace directory
      # - "/mnt/i/Shared drives/Loghi Transcriberen/fine-tuning-testing/Test source:/workspace"
      
      # Mount Docker socket for Docker-in-Docker functionality
      # - ${DOCKER_SOCKET}:${DOCKER_SOCKET}
      - /var/run/docker.sock:/var/run/docker.sock
      # Option 1: Mount Git modules (uncomment if using mounted modules)
      - ${LAYPA_MODULE}:/app/laypa
      - ${LOGHI_HTR_MODULE}:/app/loghi-htr
      - ${LOGHI_TOOLING_MODULE}:/app/loghi-tooling
      - ${PRIMA_CORE_LIBS_MODULE}:/app/prima-core-libs
      # Mount Workspace directory
      - ${WORKSPACE_PATH}:/workspace
      - ${DESTINATION_PATH}:/destination
      # Add a volume for /tmp to ensure permissions
      - loghi_temp:/tmp
    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      - ENABLE_CRON=${ENABLE_CRON:-false}
      - USE_GIT_SUBMODULES=${USE_GIT_SUBMODULES:-false}
      - WORKSPACE_PATH=/workspace
      - DESTINATION_PATH=/destination
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    # Update command to fix permissions on startup
    command: sh -c "chmod 777 /tmp && chmod 666 /var/run/docker.sock && tail -f /dev/null"
    # Uncomment if you need to use GPUs
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  loghi_temp:
    